### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by SunXiaoqian1** [ZhenYangIACAS/NMT_GAN#27]
When using a dictionary generated by BPE-processed data, the following error occurred, but there is no problem when using a dictionary generated from data that has not been processed by BPE, how should I modify it?

Traceback (most recent call last):
  File "train.py", line 83, in <module>
    train(config)
  File "train.py", line 18, in train
    du.load_vocab()
  File "/home/sxq/NMT_GAN-master/utils.py", line 56, in load_vocab
    self.src2idx, self.idx2src = load_vocab_(self.config.src_vocab, self.config.src_vocab_size)
  File "/home/sxq/NMT_GAN-master/utils.py", line 43, in load_vocab_
    vocab = [line.split()[0] for line in codecs.open(path, 'r', 'utf-8')]
IndexError: list index out of range

Looking forward to your reply.

**Comment by swordlin** [comment]
> When using a dictionary generated by BPE-processed data, the following error occurred, but there is no problem when using a dictionary generated from data that has not been processed by BPE, how should I modify it?
> 
> Traceback (most recent call last):
> File "train.py", line 83, in 
> train(config)
> File "train.py", line 18, in train
> du.load_vocab()
> File "/home/sxq/NMT_GAN-master/utils.py", line 56, in load_vocab
> self.src2idx, self.idx2src = load_vocab_(self.config.src_vocab, self.config.src_vocab_size)
> File "/home/sxq/NMT_GAN-master/utils.py", line 43, in load_vocab_
> vocab = [line.split()[0] for line in codecs.open(path, 'r', 'utf-8')]
> IndexError: list index out of range
> 
> Looking forward to your reply.

Sorry to bother you，I want to know how you got those BPE-processed datas，by Sennrich‘s subword-nmt?If so，how do you map the generated files to the file paths in these yamls? For example,I have no idea how this file named “target.bpe.txt.vocab.34432” came from.
I would appreciate to receive your reply.

**Comment by BOBOWEI2** [comment]
同问。。。。
